version: '3'

services:
  # bun server
  bun-server:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: '/app'
    volumes:
      - ./:/app  # sync data host <-> container
    ports:
      - "5173:5173"
    depends_on:
      - postgres
      - redis

  # nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - bun-server

  # redis
  redis:
    image: redis:latest
    ports:
      - "6377:6379"

  # postgres
  postgres:
    image: postgres:latest
    container_name: bun-postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
